### ISSUE TITLE
Issue using Nominatim

### ISSUE THREAD

**Issue by vschaik** [Hehehe421/NightSky#1]
Nominatim generated a permissions error. Changing the user_agent from 'myGeolocator' to another (unique) name fixes this problem. You might want to add a README file to tell the user this, or put it in a comment in the notebook.

**Comment by Hehehe421** [comment]
I tested the code but didn't get any permission errors. Would you happen to have a screenshot of the error message so I can look? Thanks!

**Comment by Hehehe421** [comment]
I tested the code but didn't get any permission errors. Would you happen to have a screenshot of the error message so I can look? Thanks!

**Comment by vschaik** [comment]
I think it is because Nomatim needs a unique user_agent name (not sure how they check) and you have the myGeolocator name. Just changing the name to something random made the error go away for me. I don't have a screen shot, but the issue is described here: https://stackoverflow.com/questions/51503389/geopy-exc-geocoderinsufficientprivileges-http-error-403-forbidden

**Comment by Hehehe421** [comment]
Thanks for the detail! Just update the fix to the main notebook by adding one more comment to replace the myGeolocator to a unique name.
