### ISSUE TITLE
tzwhere no longer works with latest numpy

### ISSUE THREAD

**Issue by vschaik** [Hehehe421/NightSky#2]
tzwhere throws an error with later version of numpy. I switched to using a package called timezonefinder which provides the same functionality.

**Comment by Hehehe421** [comment]
Thank you for opening the issue; double confirmed the issue and added the requirement.txt and readme file to specify the Numpy version and other necessary package versions.

**Comment by vschaik** [comment]
Thanks. I changed your notebook to use the following instead as I didn't want to downgrade numpy.

from timezonefinder import TimezoneFinder
...
timezone_str = TimezoneFinder().timezone_at(lat = lat, lng = long)
